repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        additional_dependencies: [types-docutils]
  - repo: https://github.com/tkoyama010/standard-readme-pre-commit
    rev: edcf5d5d60ddb7ad3edb0fbc6c2164fa35e9a8ee
    hooks:
      - id: standard-readme
